#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."

if [ ! -n "$DEVCONTAINER" ] && [ ! -n "$VIRTUAL_ENV" ];then
  echo "Creating virtual environment..."
  python3 -m venv venv
  source venv/bin/activate
fi

python3 -m pip install --requirement requirements.txt --force-reinstall


#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

scripts/pip_packages "pip<23.2,>=21.3.1"
scripts/pip_packages setuptools wheel
scripts/pip_packages --requirement requirements_lint.txt --requirement requirements_test.txt
scripts/pip_packages "homeassistant==${1:-$(jq -r .homeassistant hacs.json)}"